export interface CategoryT {
  id: number;
  name: string;
  list: string[];
}
export const data: CategoryT[] = [
  {
    id: 1,
    name: "New",
    list: [
      "All New",
      "Just Dropped",
      "New Makeup",
      "New Skin Care",
      "New Hair Care",
      "New Fragrance",
      "New Bath & Body",
      "New Tools & Brushes",
      "New Wellness",
      "New Gifts & Sets",
      "New Clean Beauty",
      "New Men’s Grooming",
      "New Mini Size",
      "New Supplements",
      "New Beauty Tech",
      "New Travel Size",
    ],
  },
  {
    id: 2,

    name: "Brand",
    list: [
      "Brand 1",
      "Brand 2",
      "Brand 3",
      "Brand 4",
      "Brand 5",
      "Brand 6",
      "Brand 7",
      "Brand 8",
      "Brand 9",
      "Brand 10",
      "Brand 11",
      "Brand 12",
      "Brand 13",
      "Brand 14",
      "Brand 15",
      "Brand 16",
      "Brand 17",
      "Brand 18",
      "Brand 19",
      "Brand 20",
      "Brand 21",
      "Brand 22",
      "Brand 23",
      "Brand 24",
    ],
  },
  {
    id: 3,
    name: "Makeup",
    list: [
      "Face Makeup",
      "Foundation",
      "Concealer",
      "Blush",
      "Bronzer",
      "Highlighter",
      "Setting Spray",
      "Eyeshadow",
      "Eyeliner",
      "Mascara",
      "Eyebrows",
      "Lipstick",
      "Lip Gloss",
      "Lip Liner",
      "Lip Balm",
      "Makeup Remover",
      "Makeup Brushes",
      "Sponges & Applicators",
      "Face Palettes",
      "Eye Palettes",
      "Contour",
      "False Eyelashes",
      "Primer",
      "BB Cream",
      "CC Cream",
      "Powder",
      "Setting Powder",
      "Brow Gel",
      "Brow Pencil",
    ],
  },
  {
    id: 4,
    name: "Skin Care",
    list: [
      "Cleanser",
      "Toner",
      "Exfoliator",
      "Serum",
      "Moisturizer",
      "Eye Cream",
      "SPF",
      "Face Oil",
      "Face Mask",
      "Night Cream",
      "Face Mist",
      "Acne Treatment",
      "Lip Care",
      "Neck Cream",
      "Sheet Mask",
      "Pore Strips",
      "Makeup Remover",
      "Sunscreen",
      "Peel",
      "Brightening",
      "Hydrating",
      "Anti-Aging",
      "Tightening",
      "Pimples Patch",
      "Spot Treatment",
      "Retinol Cream",
      "Vitamin C Serum",
      "Hyaluronic Acid",
    ],
  },
  {
    id: 5,

    name: "Fragrance",
    list: [
      "Perfume",
      "Eau de Parfum",
      "Eau de Toilette",
      "Body Mist",
      "Rollerball",
      "Cologne",
      "Solid Perfume",
      "Fragrance Oil",
      "Scented Lotion",
      "Scented Body Cream",
      "Fragrance Set",
      "Perfume Travel Size",
      "Fragrance Gift Set",
      "Men’s Cologne",
      "Women’s Perfume",
      "Unisex Fragrance",
      "Designer Fragrance",
      "Luxury Fragrance",
      "New Arrivals",
      "Best Sellers",
      "Fresh Scents",
      "Woody Scents",
      "Floral Scents",
      "Spicy Scents",
      "Warm Scents",
      "Citrus Scents",
      "Vanilla Fragrance",
    ],
  },
  {
    id: 6,

    name: "Hair",
    list: [
      "Shampoo",
      "Conditioner",
      "Hair Mask",
      "Hair Oil",
      "Leave-In Conditioner",
      "Dry Shampoo",
      "Hair Treatment",
      "Hair Serum",
      "Hair Spray",
      "Heat Protectant",
      "Scalp Treatment",
      "Hair Mousse",
      "Hair Gel",
      "Hair Pomade",
      "Hair Wax",
      "Hair Cream",
      "Hair Color",
      "Root Touch-Up",
      "Hair Toner",
      "Hair Accessories",
      "Hair Brush",
      "Hair Comb",
      "Hair Clips",
      "Hair Bands",
      "Hair Dryer",
      "Hair Straightener",
      "Hair Curling Iron",
      "Volumizer",
    ],
  },
  {
    id: 7,

    name: "Tools and Brushes",
    list: [
      "Makeup Brushes",
      "Foundation Brush",
      "Powder Brush",
      "Blush Brush",
      "Contour Brush",
      "Eyeshadow Brush",
      "Eyeliner Brush",
      "Brow Brush",
      "Blending Brush",
      "Kabuki Brush",
      "Concealer Brush",
      "Highlighter Brush",
      "Lip Brush",
      "Sponge Applicator",
      "Makeup Sponges",
      "Eyelash Curler",
      "Tweezers",
      "Facial Roller",
      "Gua Sha Tool",
      "Face Massager",
      "Brush Cleaner",
      "Mirror",
      "Makeup Bag",
      "Makeup Organizers",
      "Makeup Travel Case",
      "Brush Set",
      "Fan Brush",
    ],
  },
  {
    id: 8,

    name: "Bath and Body",
    list: [
      "Body Wash",
      "Body Scrub",
      "Body Lotion",
      "Body Butter",
      "Body Oil",
      "Shower Gel",
      "Shower Oil",
      "Bath Bombs",
      "Bath Salts",
      "Body Exfoliator",
      "Hand Wash",
      "Hand Cream",
      "Body Mist",
      "Body SPF",
      "Self Tanner",
      "Hand Sanitizer",
      "Foot Cream",
      "Body Mask",
      "Bath Accessories",
      "Bubble Bath",
      "Body Wipes",
      "Deodorant",
      "Antiperspirant",
      "Body Powder",
      "Body Roll-On",
      "Body Spray",
      "Body Shimmer",
      "Body Soufflé",
    ],
  },
  {
    id: 9,

    name: "Mini Size",
    list: [
      "Mini Makeup",
      "Mini Skincare",
      "Mini Hair Products",
      "Mini Perfume",
      "Mini Body Care",
      "Mini Tools",
      "Mini Sets",
      "Mini Gift Sets",
      "Travel Size",
      "On-the-Go",
      "Best of Minis",
      "Mini Lipstick",
      "Mini Mascara",
      "Mini Foundation",
      "Mini Moisturizer",
      "Mini Serum",
      "Mini Shampoo",
      "Mini Conditioner",
      "Mini Eyeshadow",
      "Mini Blush",
      "Mini Highlighter",
      "Mini Face Mask",
      "Mini Eye Cream",
      "Mini Fragrance Set",
      "Mini Sunscreen",
      "Mini Body Lotion",
      "Mini Deodorant",
    ],
  },
  {
    id: 10,
    name: "Beauty Under 10000",
    list: [
      "Makeup Under 10000",
      "Skincare Under 10000",
      "Fragrance Under 10000",
      "Hair Products Under 10000",
      "Body Care Under 10000",
      "Nail Polish Under 10000",
      "Tools Under 10000",
      "Gifts Under 10000",
      "Best Value Sets",
      "Travel Size Under 10000",
      "Accessories Under 10000",
      "Top Picks Under 10000",
      "Bestselling Under 10000",
      "Trending Now Under 10000",
      "New Arrivals Under 10000",
      "Sale Under 10000",
      "Mini Size Under 10000",
      "Luxury Beauty Under 10000",
      "Natural Beauty Under 10000",
      "Men’s Grooming Under 10000",
      "Wellness Under 10000",
      "Vegan Beauty Under 10000",
      "Cruelty-Free Under 10000",
      "Clean Beauty Under 10000",
      "Eco-Friendly Under 10000",
    ],
  },
  {
    id: 11,

    name: "Sale Offers",
    list: [
      "Makeup Sale",
      "Skincare Sale",
      "Fragrance Sale",
      "Hair Products Sale",
      "Body Care Sale",
      "Nail Polish Sale",
      "Tools Sale",
      "Gifts on Sale",
      "Best Deals",
      "Value Sets on Sale",
      "Top Picks on Sale",
      "Trending on Sale",
      "New Arrivals on Sale",
      "Clearance",
      "Limited Time Offers",
      "Buy One Get One Free",
      "Discounts Over 50%",
      "Holiday Sale",
      "Black Friday Deals",
      "Cyber Monday Deals",
      "Seasonal Offers",
      "Free Gifts with Purchase",
      "Weekly Specials",
      "Flash Sales",
      "VIP Exclusive Offers",
      "Luxury on Sale",
    ],
  },
];
