export const heroCardsData = [
  {
    image: "/assets/home/hero1.png",
    title: "Discover Top Brands",
    description: "Explore the best beauty brands in one place",
    background: "#edc1cf",
    path: "/brands",
  },
  {
    image: "/assets/home/hero2.png",
    title: "Latest Arrivals",
    description: "Stay ahead with the newest beauty products",
    background: "#d1c1b0",
    path: "/new-categories",
  },
  {
    image: "/assets/home/hero3.png",
    title: "Must-Have Picks",
    description: "Shop our top-rated beauty essentials",
    background: "#edc1cf",
    path: "/products",
  },
  {
    image: "/assets/home/hero4.png",
    title: "Nadi's Favorites",
    description: "Handpicked beauty products just for you",
    background: "#b2cbb7",
    path: "/nadi-recommendation",
  },
  {
    image: "/assets/home/hero5.png",
    title: "Trending Now",
    description: "See what's hot in beauty right now",
    background: "#f6e7df",
    path: "/products",
  },
  {
    image: "/assets/home/hero6.png",
    title: "Best of Beauty",
    description: "Indulge in luxury beauty must-haves",
    background: "#d7b3a3",
    path: "/products",
  },
  {
    image: "/assets/home/hero7.png",
    title: "Exclusive Brands",
    description: "Shop premium beauty brands with us",
    background: "#ede1c1",
    path: "/brands",
  },
  {
    image: "/assets/home/hero8.png",
    title: "New & Noteworthy",
    description: "Fresh arrivals you need to check out",
    background: "#f5ebdc",
    path: "/new-categories",
  },
  {
    image: "/assets/home/hero9.png",
    title: "Editor’s Choice",
    description: "Our experts’ top beauty recommendations",
    background: "#e5e7e6",
    path: "/nadi-recommendation",
  },
];
