import "/assets/products/product1.png";
import "/assets/products/product2.png";
import "/assets/products/product3.png";
import "/assets/products/product4.png";

export const products = [
  {
    id: 1,
    title: "Summer Fridays",
    tags: ["New", "Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product1.png",
    price: 1000,
  },
  {
    id: 2,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product2.png",
    price: 1500,
  },
  {
    id: 3,
    title: "Summer Fridays",
    tags: ["New"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 2000,
  },
  {
    id: 4,
    title: "Summer Fridays",
    tags: ["New", "Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product4.png",
    price: 2500,
  },
  {
    id: 5,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product1.png",
    price: 3000,
  },
  {
    id: 6,
    title: "Summer Fridays",
    tags: ["Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product2.png",
    price: 3500,
  },
  {
    id: 8,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 9,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 10,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 11,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 12,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 13,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 14,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 15,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 16,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 17,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 18,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 19,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 20,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 21,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 22,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 23,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 24,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 25,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 26,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 27,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 28,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 29,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 30,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 31,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 32,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 33,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 34,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 35,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 36,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
];
