import "/assets/products/product1.png";
import "/assets/products/product2.png";
import "/assets/products/product3.png";
import "/assets/products/product4.png";

export const products = [
  {
    id: 1,
    title: "Summer Fridays",
    tags: ["New", "Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product1.png",
    price: 1000,
  },
  {
    id: 2,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product2.png",
    price: 1500,
  },
  {
    id: 3,
    title: "Summer Fridays",
    tags: ["New"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 2000,
  },
  {
    id: 4,
    title: "Summer Fridays",
    tags: ["New", "Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product4.png",
    price: 2500,
  },
  {
    id: 5,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product1.png",
    price: 3000,
  },
  {
    id: 6,
    title: "Summer Fridays",
    tags: ["Limited Edition"],
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product2.png",
    price: 3500,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
  {
    id: 7,
    title: "Summer Fridays",
    desc: "Dream Lip Oil for Moisturing Sheer...",
    image: "/assets/products/product3.png",
    price: 4000,
  },
];
